version: "3"

services:
  php:
    build:
      context: docker/php
    volumes:
      - .:/app
    working_dir: /app
    container_name: core_php

  nginx:
    image: nginx:1.15
    ports:
      - 127.0.0.1:${NGINX_PORT}:80
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    container_name: core_nginx

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3333:3306"

  rabbitmq:
    image: rabbitmq:3.7.7-management
    hostname: rabbitmq
    volumes:
      - ./docker/rabbitmq/data:/var/lib/rabbitmq
    ports:
      - 127.0.0.1:${RABBIT_MQ_MANAGEMENT_PORT}:15672
    container_name: core_rabbitmq

networks:
  default:
    external:
      name: core